//public is a keyword to define access level
//known as access modifier, there are couple of them we will learn later
// class : indicate this is a class
// phone : identifier, the name of the class
// { any code need to go in here, can not go outside}

public class Phone {
  // a phone has below 
  // attributes or characteristics
  // brand, price, memory size
  // instance variable |field
    Public String brand ;  
    Public Decimal Price ;
    Public Integer memorySize ;
}